### ISSUE TITLE
Improvement for return types for the API

### ISSUE THREAD

**Issue by emmaLP** [voiceittech/VoiceIt2-Java#5]
The wrapper could be improved to return a POJO object of the response rather than a string so that   it be easier to maintain for the end user should the api change to include/exclude response fields.

**Comment by bravecorvus** [comment]
Thank you for your feedback! After discussing this internally, we want our customers to have the ability to plug in their own JSON object binder as Java does not have a good standard library implementation compared to something like Go or Node.
